### PR TITLE
Fest swing jide

### PR DESCRIPTION
**Pull request by gschrader**
oops, the last pull request was closed since I made a mistake originally and was working off of master.

### CODE REVIEW

**Comment by gschrader** [comment]
previous pull request https://github.com/joel-costigliola/assertj-swing/pull/150

**Comment by croesch** [comment]
I'm going to clean it up a bit and merge it as soon as the licence requirements are met. Thanks for your patience!

**Comment by gschrader** [comment]
Thanks!

**Comment by croesch** [comment]
My pleasure ;-)

Sorry again for the big delay!

**Pull request closed without merging**
