### PR TITLE
Bump assertj-core to version 3.17.0

### PR DESCRIPTION
**Pull request by scordio**
This upgrade together with a new release of AssertJ Swing would address the issue in joel-costigliola/assertj-core#1974.

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Good work as a first time contributor @scordio! 😆

**Comment by scordio** [comment]
@joel-costigliola @croesch it would be great if any of you could perform a release with this fix.

**Comment by tifhorn** [comment]
@scordio @joel-costigliola 
Thank you for your time on this topic, I'd be grateful for a release including this fix :)

**Comment by scordio** [comment]
Sure, as we plan to release `assertj-core` 3.17.1 in the upcoming weekend, let's see if @joel-costigliola has time to also squeeze in `assertj-swing`.

**Comment by henri-tremblay** [comment]
Thanks guys! I looked quickly at open issues but failed to find this. Will be waiting for the release :-)

**Pull request merged**
