### PR TITLE
IntrospectionComponentFormatter should show real class name for anonymous classes

### PR DESCRIPTION
**Pull request by timmikk**
Currently IntrospectionComponentFormatter shows anonymous classes with following format: base.component.package.BaseComponent$1. This does not give enough feedback of what the component really is. In my solution the real class name is digged from the anonymous class.

### CODE REVIEW

**Comment by croesch** [comment]
Could you give a basic code snippet where this helps you? I like the idea but with your approach the information is lost that the component is created as an anonymous class. I would like to see an output that contains both, that it's an anonymous class and what type it is.

**Comment by timmikk** [comment]
Sorry for long delay.

I have been working quite a lot with components that wrap some other display component as anonymous classes. In many cases it is very important to know the real type of the class for example when solving some errors with finders and matchers. Also when working with third party libraries it is even more difficult to find out the real types of the components.

Simple example of anonymous component:

```java
public class CustomTextField extends JPanel {
    JTextField textField = new JTextField() {
        @Override
        public void setText(String t) {
            super.setText(t+" - customized");

        }
    };

    public static void main(String[] args) {
        System.out.println(new CustomTextField().textField.getClass().toString());
        System.out.println(new CustomTextField().textField.getClass().getSuperclass().toString());
    }
}
```

And the output:
```
class org.custom.CustomTextField$1
class javax.swing.JTextField
```

**Comment by croesch** [comment]
Don't worry about the delay :-)

Why don't you write..

```
public class CustomTextField extends JTextField {
        @Override
        public void setText(String t) {
        }
}
```

That would help in many ways. And then you would not need the anonymous class.

**Comment by timmikk** [comment]
You are right and probably I would do that way if I could. But unfortunately I don't have the possibility to change the component hierarchies as I'm working with legacy code with lots of these wrapped components.

**Comment by croesch** [comment]
Added your code, changed it a bit. Let me know if this helps you :)

**Comment by croesch** [comment]
Thanks for your help!

**Pull request closed without merging**
